#!/bin/python3

alphabet = 'abcdefghijklmnopqrstuvwxyz'

newMessage = ''

message  = input('Please input your decrypted message: ')

position = alphabet.find(message)

key = input('Please enter your key: ')
newKey = int(key)

for character in message:
  if character in alphabet:
    position = alphabet.find(character)
    newPosition = (position - newKey) % 26
    newCharacter = alphabet[newPosition]
    newMessage += newCharacter
  
  else:
    newMessage += character

print('The decrypted message is: ',  newMessage)
